sudo: false

# Use as OS Ubuntu 18.04 (bionic)
dist: bionic

# We should actually not specify a compiler
compiler: gcc

install: 
- mkdir build
- cd build
- cmake .. -DDOWNLOAD_JLINK=OFF

script:
- make

git:
    depth: 3

# blocklist
branches:
    except:
    - gh-pages
